project_name: test
sample_name: frog_1
schema_path: pipestat_output_schema.yaml
results_file_path: "/ABSOLUTEPATH/"  #this is an absolute path for now
database:
  dialect: postgresql
  driver: psycopg2
  name: pipestat-test
  user: postgres
  password: pipestat-password
  host: 127.0.0.1
  port: 5432
