results_file_path: /home/nsheff/code/hello_looper/basic-pipestat/./results.yaml
flag_file_dir: /home/nsheff/code/hello_looper/basic-pipestat/./results/flags
output_dir: /home/nsheff/code/hello_looper/basic-pipestat/./results
record_identifier: frog_2
schema_path: /home/nsheff/code/hello_looper/basic-pipestat/./pipeline_pipestat/pipestat_output_schema.yaml
pipeline_name: test_pipe
pipeline_type: sample
