name: looper_advanced_test
pep_version: "2.0.0"
sample_table: annotation_sheet.csv

looper:
  all:
    output_dir: "results"
  cli:
    runp:
      pipeline_interfaces:
      - pipeline/pipeline_interface1_project.yaml
      - pipeline/pipeline_interface2_project.yaml
sample_modifiers:
  append:
    attr: "val"
    pipeline_interfaces:
      - pipeline/pipeline_interface1_sample.yaml
      - pipeline/pipeline_interface2_sample.yaml
  derive:
    attributes: [read1, read2]
    sources:
      SRA_1: "{SRR}_1.fastq.gz"
      SRA_2: "{SRR}_2.fastq.gz"
